<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>AI Interview Mocker</title>
  <link rel="stylesheet" href="css/style.css">

  <script>
  function goToSection(className) {
    // const section = document.getElementById(className);
    const section = document.querySelector(`.${className}`);
    if (section) {
      section.scrollIntoView({ behavior: 'smooth' });
    }
  }
</script>

</head>
<body>

  <div class="logo">
    <img src="images/logo.png" alt="logo">
    <h1>AI Mock Interview</h1>
      <!-- nav --> 
      <div class="radio-inputs">
        <label class="radio">
          <input type="radio" name="radio" checked="" onclick="goToSection('hero-section')">
          <span class="name">Home</span>
        </label>
        <label class="radio">
          <input type="radio" name="radio" checked="" onclick="goToSection('features-title')">
          <span class="name">Features</span>
        </label>
        <label class="radio">
          <input type="radio" name="radio" onclick="goToSection('footer-col')">
          <span class="name">Contacts</span>
        </label>
        <label class="radio">
          <input type="radio" name="radio" onclick="goToSection('feature-card')">
          <span class="name">How it Works?</span>
        </label>
        <label class="radio">
          <input type="radio" name="radio" onclick="window.location.href='register.php'">
          <span class="name">Register</span>
        </label>
      </div>
  </div>



  <!-- Hero Section -->
  <div class="hero-section">
    <!-- Image -->
    <div class="hero-image">
      <img src="images/main.png" alt="AI Interview Mocker image">
    </div>

    <!-- Content -->
    <div class="hero-content">
      <h2>AI Interview Mocker</h2>
      <p>
        Get ready for your next interview with realistic <br>
        mock interviews powered by AI. Practice with dynamic, <br>
        real-world questions and improve your interview skills today!
      </p>
      <a href="login.php" class="button">Sign In</a>
    </div>
  </div>

  <section class="features-section">
  <h2 class="features-title">Our Features</h2>
  <div class="features-underline"></div>

  <div class="features-grid">
    <!-- Left Column -->
    <div class="features-column">
      <div class="feature-box">
        <div class="feature-icon"></div>
        <div>
          <h3>AI-Powered Questioning</h3>
          <p>Our AI dynamically generates interview questions based on your job role, experience level, and industry. Unlike traditional mock interviews that follow a fixed script, our AI adapts the difficulty and content based on your responses, providing a truly interactive experience.</p>
        </div>
      </div>
      <div class="feature-box">
        <div class="feature-icon"></div>
        <div>
          <h3>Speech to Text Analysis</h3>
          <p>Our AI evaluates your voice clarity, confidence, and fluency, helping you refine your communication skills. It provides instant feedback on pronunciation, filler words, and pace, ensuring that you sound confident and professional during real interviews.</p>
        </div>
      </div>
    </div>

    <!-- Center Image -->
    <figure class="features-banner">
      <img
        src="images/feautres-banner.png"
        width="369"
        height="318"
        loading="lazy"
        alt="Features Banner"
        class="w-100 banner-animation"
      />
    </figure>

    <!-- Right Column -->
    <div class="features-column">
      <div class="feature-box">
        <div class="feature-icon"></div>
        <div>
          <h3>Webcam Integration</h3>
          <p>To simulate an authentic interview, the platform uses your webcam for face detection and provides live video preview during the session. It ensures you're prepared for any interview that requires a visual presence.</p>
        </div>
      </div>
      <div class="feature-box">
        <div class="feature-icon"></div>
        <div>
          <h3>Real-Time Feedback</h3>
          <p>Receive instant feedback after every answer, including detailed ratings and personalized suggestions for improvement. The AI evaluates the quality of your responses, communication, and even body language during the interview.</p>
        </div>
      </div>
    </div>
  </div>
</section>


  <!-- Features Section -->
  <div class="features-section">
    <h2>How It Works</h2>
    <div class="features-grid">
      <div class="feature-card">
        <h3>Realistic Mock Interviews</h3>
        <p>
          Get realistic interview questions generated by our advanced AI to simulate actual interview scenarios.
        </p>
      </div>
      <div class="feature-card">
        <h3>Personalized Feedback</h3>
        <p>
          Receive personalized feedback on your answers to improve your responses and ace your interview.
        </p>
      </div>
      <div class="feature-card">
        <h3>Progress Tracking</h3>
        <p>
          Track your interview preparation progress over time with detailed reports to monitor your improvement.
        </p>
      </div>
    </div>
  </div>
  
  <!-- footer -->




<div class="footer">
  <div class="container">
    <div class="footer-col intro">
      <h4 style="font-family:'Brushed Script';font-size: 30px;">Team AI Mock Interview</h4>
      <p>
        Our platform offers realistic, AI-driven interview practice to help you build
        confidence and improve your skills. Get personalized questions, real-time feedback,
        and performance insights for technical, HR, and aptitude interviews. With AI-powered
        analysis and resume reviews, we ensure you're fully prepared to ace your next interview.
        Start practicing today!
      </p>
      <div class="social-icons">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div class="footer-col">
      <h4>Our links</h4>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">About Us</a></li>
        <li><a href="#">Team</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Our Work</h4>
      <ul>
        <li><a href="#">Strategy & Research</a></li>
        <li><a href="#">Aptitude</a></li>
        <li><a href="#">Web Based preparation</a></li>
        <li><a href="#">Real-time feedback</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Other links</h4>
      <ul>
        <li><a href="#">Developer</a></li>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms & Conditions</a></li>
      </ul>
    </div>

    <div class="footer-col">
      <h4>Contact Us</h4>
      <ul>
        <li><span class="dot"></span> 9307872262</li>
        <li><span class="dot"></span> gorea722@gmail.com</li>
        <li><span class="dot"></span> Nashik</li>
      </ul>
    </div>
  </div>
</div>


  <?php
    include "footer.php";
  ?>
</body>
</html>
